### ISSUE TITLE
Github project name alignment

### ISSUE THREAD

**Issue by davidkhala** [Hyperledger-TWGC/tjfoc-gm#11]
@yzwyzwyzw1 @czdsdo 
志伟，陈序：此issue用于讨论项目重命名事宜
我的想法是可以改成tjfoc-gm
此外我个人有个问题是foc分别是哪几个单词的缩写？

**Comment by yzwyzwyzw1** [comment]
支持



---Original---

**Comment by czdsdo** [comment]
tongji fintech open chain

**Comment by davidkhala** [comment]
Good to see code name changed. 
We might need further code alignment, especially go package name.

**Comment by davidkhala** [comment]
Resolved, close
