### ISSUE TITLE
cherryPick from https://github.com/tjfoc/gmsm:master

### ISSUE THREAD

**Issue by davidkhala** [Hyperledger-TWGC/tjfoc-gm#13]
今天尝试了一下 cherry pick ，发现主要的改动在sm2.go上，这次修复范围比较大也有很长的冲突段落
@czdsdo   不知道这部分工作稳定了么？如果还没稳定，这个issue可以先挂着。

**Comment by czdsdo** [comment]
关于master上的新增commit，我也直接放到这dev-fabric里了。
由于代码结构不同有所改动，master那由于考虑到兼容的问题，暂没有对代码结构进行改动，后续发布新版本不兼容更新的时候会考虑把dev-fabric的改动merge到master上去。

**Comment by davidkhala** [comment]
原来是这样反向维护的，了解了
