### ISSUE TITLE
Bug: import cycle

### ISSUE THREAD

**Issue by davidkhala** [Hyperledger-TWGC/tjfoc-gm#15]
When I try to use import private pem in SM2 test. There is cyclic import. 

```
# github.com/Hyperledger-TWGC/tjfoc-gm/sm2
FAIL	github.com/Hyperledger-TWGC/tjfoc-gm/sm2 [setup failed]
FAIL
package github.com/Hyperledger-TWGC/tjfoc-gm/sm2 (test)
	imports github.com/Hyperledger-TWGC/tjfoc-gm/x509
	imports github.com/Hyperledger-TWGC/tjfoc-gm/sm2: import cycle not allowed in test
```
@yzwyzwyzw1 关于SM2的函数按道理应该都闭包在SM2 package里面，放在x509是有特殊考虑么？

**Comment by yzwyzwyzw1** [comment]
关于sm2生成pem的程序不属于国密规范内容，但是在fabric要支持生成对应私钥以及公钥的证书，调用函数的目录在x509目录下，所以为了与fabric代码统一，所以将这部分程序也放到了国密包的x509目录下。



---Original---

**Comment by davidkhala** [comment]
了解，我自己调整了代码写法避免了这个bug
