### ISSUE TITLE
SM4.go: unused function WriteKeytoMem, EncryptBlock, DecryptBlock

### ISSUE THREAD

**Issue by davidkhala** [Hyperledger-TWGC/tjfoc-gm#4]
- `WriteKeytoMem` has strong similarity to another function `WriteKeyToPem` bothin name and code lines. They differ only in the return values type. Please consider merge them into single one
- `EncryptBlock`, `DecryptBlock` are both not covered in tests. In SM4, it use `type Block`
   -    `Encrypt(dst, src []byte)`
   - 	`Decrypt(dst, src []byte)`

**Comment by davidkhala** [comment]
in SM4 we have both Sm4Cipher and SM4Key. Consider merge into single type

**Comment by czdsdo** [comment]
commit: 7caf961
