### ISSUE TITLE
可否添加 sm3.Size sm3.BlockSize 包常量

### ISSUE THREAD

**Issue by xuyang2** [Hyperledger-TWGC/tjfoc-gm#53]
可否给 `package sm3` 添加包常量
```
const Size = 32
const BlockSize = 64
```

相关代码：
- https://github.com/Hyperledger-TWGC/tjfoc-gm/blob/4b29e623015537b75b5fd1938ce3a17800c7c9a1/sm3/sm3.go#L33-L40

Go 标准库的做法：
- https://github.com/golang/go/blob/1afa432ab93aa9adb2e0f04b6c15eb654762d652/src/crypto/sha512/sha512.go#L28-L42
- https://github.com/golang/go/blob/1afa432ab93aa9adb2e0f04b6c15eb654762d652/src/crypto/sha256/sha256.go#L21-L28
- https://github.com/golang/go/blob/1afa432ab93aa9adb2e0f04b6c15eb654762d652/src/crypto/md5/md5.go#L24-L28

上游 issue 见 https://github.com/tjfoc/gmsm/issues/142

**Comment by SamYuan1990** [comment]
感谢提出问题和建议。
在作出决定前，我想了解下更多的相关内容，如果这里使用常量：
- 是否影响性能？
- 常量是否复用？
- 其他？
我理解这里应该是这样做有什么好处？
比如golang这样做了之后从而得到了什么样子的好处。
而不是因为别人也这么做了我们才这样做。

**Comment by xuyang2** [comment]
@SamYuan1990 
常量是为了方便使用，比如可以
``` sz := sm3.Size ```
而不用
```
var h sm3.SM3
sz := h.Size()
```
