### ISSUE TITLE
GOARCH=arm64 构建失败

### ISSUE THREAD

**Issue by xuyang2** [Hyperledger-TWGC/tjfoc-gm#54]
```bash
~/code/github.com/Hyperledger-TWGC/tjfoc-gm (dev-fabric) $ GOOS=linux GOARCH=arm64 go build -v github.com/Hyperledger-TWGC/tjfoc-gm/sm3
github.com/Hyperledger-TWGC/tjfoc-gm/sm3
# github.com/Hyperledger-TWGC/tjfoc-gm/sm3
sm3/sm3block.go:15:2: undefined: block
```

似乎是 [sm3 performance optimization #46 ](https://github.com/Hyperledger-TWGC/tjfoc-gm/pull/46) 时，
只写了 amd64, 386 的汇编，但是把用于其它架构的纯go实现整个删掉了。

另外建议 `sm3block_decl.go` `sm3block_generic.go` 中只放 build tag 和必要的方法声明。

见：
- https://github.com/emmansun/gmsm/blob/main/sm3/sm3block_decl.go
- https://github.com/emmansun/gmsm/blob/main/sm3/sm3block_generic.go
- https://github.com/golang/go/blob/master/src/crypto/sha512/sha512block_decl.go
- https://github.com/golang/go/blob/master/src/crypto/sha512/sha512block_generic.go

**Comment by SamYuan1990** [comment]
@czdsdo , please advise.
