### ISSUE TITLE
try   https://github.com/emmansun/gmsm

### ISSUE THREAD

**Issue by mei-rune** [Hyperledger-TWGC/tjfoc-gm#61]

**Comment by SamYuan1990** [comment]
?

**Comment by mei-rune** [comment]
Hyperledger-TWGC组织有关注  tjfoc-gm  和 ccs-gm
而 tjfoc-gm 已经很久不维护了， 这个 https://github.com/emmansun/gmsm  功能很全， bug 修复也很及时， 你们可以关注一下

只是想告诉你们一下
